<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width" />
    </head>
    <body style="width: 100% !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; color: #222222; display: block; font-family: 'Helvetica', 'Arial', sans-serif; font-weight: normal; text-align: left; line-height: 19px; font-size: 14px; margin: 0; padding: 0;"><style type="text/css">
            a:hover {
                color: #2795b6 !important;
            }
            a:active {
                color: #2795b6 !important;
            }
            a:visited {
                color: #2ba6cb !important;
            }
            h1 a:active {
                color: #2ba6cb !important;
            }
            h2 a:active {
                color: #2ba6cb !important;
            }
            h3 a:active {
                color: #2ba6cb !important;
            }
            h4 a:active {
                color: #2ba6cb !important;
            }
            h5 a:active {
                color: #2ba6cb !important;
            }
            h6 a:active {
                color: #2ba6cb !important;
            }
            h1 a:visited {
                color: #2ba6cb !important;
            }
            h2 a:visited {
                color: #2ba6cb !important;
            }
            h3 a:visited {
                color: #2ba6cb !important;
            }
            h4 a:visited {
                color: #2ba6cb !important;
            }
            h5 a:visited {
                color: #2ba6cb !important;
            }
            h6 a:visited {
                color: #2ba6cb !important;
            }
            .button:hover table td {
                background: #2795b6 !important;
            }
            .tiny-button:hover table td {
                background: #2795b6 !important;
            }
            .small-button:hover table td {
                background: #2795b6 !important;
            }
            .medium-button:hover table td {
                background: #2795b6 !important;
            }
            .large-button:hover table td {
                background: #2795b6 !important;
            }
            .button:hover {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .button:active {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .button:visited {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .tiny-button:hover {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .tiny-button:active {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .tiny-button:visited {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .small-button:hover {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .small-button:active {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .small-button:visited {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .medium-button:hover {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .medium-button:active {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .medium-button:visited {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .large-button:hover {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .large-button:active {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .large-button:visited {
                color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;
            }
            .secondary:hover table td {
                background: #d0d0d0 !important;
            }
            .success:hover table td {
                background: #457a1a !important;
            }
            .alert:hover table td {
                background: #970b0e !important;
            }
            .facebook:hover table td {
                background: #2d4473 !important;
            }
            .twitter:hover table td {
                background: #0087bb !important;
            }
            .google-plus:hover table td {
                background: #CC0000 !important;
            }
            @media only screen and (max-width: 600px) {
                table[class="body"] img {
                    width: auto !important; height: auto !important;
                }
                table[class="body"] .container {
                    width: 95% !important;
                }
                table[class="body"] .row {
                    width: 100% !important; display: block !important;
                }
                table[class="body"] .wrapper {
                    display: block !important; padding-right: 0 !important;
                }
                table[class="body"] .columns {
                    table-layout: fixed !important; float: none !important; width: 100% !important; padding-right: 0px !important; padding-left: 0px !important; display: block !important;
                }
                table[class="body"] .column {
                    table-layout: fixed !important; float: none !important; width: 100% !important; padding-right: 0px !important; padding-left: 0px !important; display: block !important;
                }
                table[class="body"] .wrapper.first .columns {
                    display: table !important;
                }
                table[class="body"] .wrapper.first .column {
                    display: table !important;
                }
                table[class="body"] table.columns td {
                    width: 100%;
                }
                table[class="body"] table.column td {
                    width: 100%;
                }
                table[class="body"] td.offset-by-one {
                    padding-left: 0 !important;
                }
                table[class="body"] td.offset-by-two {
                    padding-left: 0 !important;
                }
                table[class="body"] td.offset-by-three {
                    padding-left: 0 !important;
                }
                table[class="body"] td.offset-by-four {
                    padding-left: 0 !important;
                }
                table[class="body"] td.offset-by-five {
                    padding-left: 0 !important;
                }
                table[class="body"] td.offset-by-six {
                    padding-left: 0 !important;
                }
                table[class="body"] td.offset-by-seven {
                    padding-left: 0 !important;
                }
                table[class="body"] td.offset-by-eight {
                    padding-left: 0 !important;
                }
                table[class="body"] td.offset-by-nine {
                    padding-left: 0 !important;
                }
                table[class="body"] td.offset-by-ten {
                    padding-left: 0 !important;
                }
                table[class="body"] td.offset-by-eleven {
                    padding-left: 0 !important;
                }
                table[class="body"] .expander {
                    width: 9999px !important;
                }
                table[class="body"] center {
                    min-width: 0 !important;
                }
                table[class="body"] .hide-for-small {
                    display: none !important;
                }
                table[class="body"] .show-for-desktop {
                    display: none !important;
                }
                table[class="body"] .show-for-small {
                    display: inherit !important;
                }
                table[class="body"] .hide-for-desktop {
                    display: inherit !important;
                }
                table[class="body"] .right-text-pad {
                    padding-left: 10px !important;
                }
                table[class="body"] .left-text-pad {
                    padding-right: 10px !important;
                }
            }
        </style>
        <table class="body" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; height: 100%; width: 100%; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td class="center" align="center" valign="top" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: center; padding: 0;">
                    <center style="width: 100%; min-width: 580px; background-color: #D5D6D6">


                        <table class="row header" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; position: relative; background: #174fa1; padding: 0px;" bgcolor="#3b3dcc"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td class="center" align="center" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: center; padding: 0;" valign="top">
                                    <center style="width: 100%; min-width: 580px;">

                                        <table class="container" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: inherit; width: 580px; margin: 0 auto; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td class="wrapper last" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; position: relative; padding: 10px 0px 0px;" align="left" valign="top">

                                                    <table class="twelve columns" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 580px; margin: 0 auto; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td class="six sub-columns" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 50% !important; padding: 0px 3.448276% 10px 0px;" align="left" valign="top">
                                                                <img src="http://grupomol.azdesarrollo.com.ar/img/marcasinfondo.png" style="outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; width: auto; max-width: 100%; float: left; clear: both; display: block;" align="left" /></td>
                                                            <td class="six sub-columns last" align="right" style="text-align: right; vertical-align: middle; word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; width: 50% !important; padding: 0px 0px 10px;" valign="middle">
                                                                <span class="template-label" style="color: #ffffff; font-weight: bold; font-size: 17px;">Clipping GrupoMol</span>
                                                            </td>
                                                            <td class="expander" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; visibility: hidden; width: 0px; padding: 0;" align="left" valign="top"></td>

                                                        </tr></table></td>
                                            </tr></table></center>
                                </td>
                            </tr></table><br /><table class="container" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: inherit; width: 580px; margin: 0 auto; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; padding: 0;" align="left" valign="top">

                                    <!-- content start -->
                                    <table class="row" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; position: relative; display: block; padding: 0px;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td class="wrapper last" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; position: relative; padding: 10px 0px 0px;" align="left" valign="top">

                                                <table class="twelve columns" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 580px; margin: 0 auto; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; padding: 0px 0px 10px;" align="left" valign="top">

                                                            <h3 style="color: #222222; display: block; font-family: 'Helvetica', 'Arial', sans-serif; font-weight: normal; text-align: left; line-height: 1.3; word-break: normal; font-size: 37px; margin: 0; padding: 0;" align="left"><?php echo $this->titulo ?></h3>
                                                            <p class="lead" style="color: #222222; display: block; font-family: 'Helvetica', 'Arial', sans-serif; font-weight: normal; text-align: left; line-height: 19px; font-size: 14px; margin: 0; padding: 0 0 10px;" align="left"><?php echo $this->copete ?></p>
                                                        </td>
                                                        <td class="expander" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; visibility: hidden; width: 0px; padding: 0;" align="left" valign="top"></td>
                                                    </tr></table></td>
                                        </tr></table>
                                    
                                            
                                            <?php foreach ($this->imagenes as $imagen) : ?>
                                    <table class="row callout" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; position: relative; display: block; padding: 0px;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left">

                                               

                                            <td class="wrapper last" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; position: relative; padding: 10px 0px 0px;" align="left" valign="top">
                                                <table class="twelve columns" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 580px; margin: 0 auto; padding: 0;">
                                                    <tr style="vertical-align: top; text-align: left; padding: 0;" align="left">
                                                        <td class="panel" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; background: #D5D6D6; padding: 10px; border: 1px solid #b9e5ff;" align="left" bgcolor="#ECF8FF" valign="top">
                                                            <img width="580" height="300" src="<?php echo 'http://grupomol.azdesarrollo.com.ar/img/imagenesInformes/' . $imagen['url'] ?>" style="outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; width: auto; max-width: 100%; float: left; clear: both; display: block;" align="left" />
                                                            <p style="color: #222222; display: block; font-family: 'Helvetica', 'Arial', sans-serif; font-weight: normal; text-align: left; line-height: 19px; font-size: 14px; margin: 0; padding: 0 0 10px;" align="left"><?php echo $imagen['descripcion'] ?></p>
                                                        </td>
                                                        <td class="expander" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; visibility: hidden; width: 0px; padding: 0;" align="left" valign="top"></td>
                                                    </tr>
                                                </table>
                                            </td>

                                                

                                        </tr></table>
                                    <?php endforeach; ?>
                                    
                                    
                                    <table class="row" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; position: relative; display: block; padding: 0px;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td class="wrapper last" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; position: relative; padding: 10px 0px 0px;" align="left" valign="top">

                                                <table class="twelve columns" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 580px; margin: 0 auto; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; padding: 0px 0px 10px;" align="left" valign="top">
                                                            <p style="color: #222222; display: block; font-family: 'Helvetica', 'Arial', sans-serif; font-weight: normal; text-align: left; line-height: 19px; font-size: 14px; margin: 0; padding: 0 0 10px;" align="left"><?php echo $this->resumen ?></p>
                                                        </td>
                                                        <td class="expander" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; visibility: hidden; width: 0px; padding: 0;" align="left" valign="top"></td>
                                                    </tr></table></td>
                                        </tr></table><table class="row footer" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; position: relative; display: block; padding: 0px;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td class="wrapper" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; position: relative; background: #ebebeb; padding: 10px 20px 0px 0px;" align="left" bgcolor="#ebebeb" valign="top">

                                                <table class="six columns" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 280px; margin: 0 auto; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td class="left-text-pad" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; padding: 0px 0px 10px 10px;" align="left" valign="top">

                                                            <h5 style="color: #222222; display: block; font-family: 'Helvetica', 'Arial', sans-serif; font-weight: normal; text-align: left; line-height: 1.3; word-break: normal; font-size: 23px; margin: 0; padding: 0 0 10px;" align="left">Con&eacute;ctese con nosotros</h5>

                                                            <a class="tiny-button facebook" href="#" style="color: #ffffff !important; font-family: Helvetica, Arial, sans-serif; text-decoration: none;">
                                                                <table style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; overflow: hidden; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: center; display: block; width: auto !important; font-weight: normal; text-decoration: none; font-family: Helvetica, Arial, sans-serif; color: #ffffff; font-size: 12px; background: #3b5998; padding: 5px 10px; border: 1px solid #2d4473;" align="center" bgcolor="#3b5998" valign="top">
                                                                            Grupo MOl
                                                                        </td>
                                                                    </tr></table></a>

                                                            <br /></td>
                                                        <td class="expander" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; visibility: hidden; width: 0px; padding: 0;" align="left" valign="top"></td>
                                                    </tr></table></td>
                                            <td class="wrapper last" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; position: relative; background: #ebebeb; padding: 10px 0px 0px;" align="left" bgcolor="#ebebeb" valign="top">

                                                <table class="six columns" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 280px; margin: 0 auto; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td class="last right-text-pad" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; padding: 0px 0px 10px;" align="left" valign="top">
                                                            <h5 style="color: #222222; display: block; font-family: 'Helvetica', 'Arial', sans-serif; font-weight: normal; text-align: left; line-height: 1.3; word-break: normal; font-size: 23px; margin: 0; padding: 0 0 10px;" align="left">Informaci&oacute;n de Contacto:</h5>
                                                            <p style="color: #222222; display: block; font-family: 'Helvetica', 'Arial', sans-serif; font-weight: normal; text-align: left; line-height: 19px; font-size: 14px; margin: 0; padding: 0 0 10px;" align="left">Email: <a href="grupomol.com.ar" style="color: #2ba6cb; text-decoration: none !important;">grupomol.com.ar</a></p>
                                                        </td>          
                                                        <td class="expander" style="word-break: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; visibility: hidden; width: 0px; padding: 0;" align="left" valign="top"></td>
                                                    </tr></table></td>
                                        </tr></table><!-- container end below --></td>
                            </tr></table></center>
                </td>
            </tr></table></body>
</html>
