<div class="titulo-y-acciones">
    <h1>Informes</h1>
    <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'informes', 'action' => 'nuevo'),null,true) ?>">
        <img src="<?php echo $this->baseUrl() . '/img/add_to_folder.png' ?>" class="pull-right">
    </a>
</div>

<?php if (count($this->mensajes)) : ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <ul id="messages">
            <?php foreach ($this->mensajes as $message) : ?>
                <li><?php echo $this->escape($message); ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<br>
<table class="table">
    <tr>
        <th>Título</th>
        <th>Acciones</th>
    </tr>

    <?php
    if ($this->informes != null) :
        foreach ($this->informes as $informe) :
            ?>
            <tr>
                <td><?php echo $informe->getTitulo() ?></td>
                <td>
                <a data-toggle="tooltip" title="Ver Detalle" class="pull-left" href="<?php echo $this->url(array('id' => $informe->getId()),'detalle',true) ?>">
                    <img src="<?php echo $this->baseUrl() . '/img/folder_full.png' ?>" class="pull-right">
                </a>
                <a data-toggle="tooltip" title="Enviar Mail" class="pull-left" href="<?php echo $this->url(array('id' => $informe->getId()),'enviar-mail',true) ?>">
                    <img src="<?php echo $this->baseUrl() . '/img/mail_send24.png' ?>" class="pull-right">
                </a>
            </td>
            </tr>

        <?php
        endforeach;
    else :
        ?>
        <tr><td colspan="4">No se encontraron registros</td>
            
        </tr>
<?php endif; ?>

</table>